version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - SECRET_KEY=${SECRET_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_REPO=${GITHUB_REPO}
      - ALGORITHM=${ALGORITHM}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PROVIDER=${PROVIDER}
    volumes:
      - ./backend/local_packages/lida:/usr/local/lib/python3.9/site-packages/lida
      - ./backend/local_packages/llmx:/usr/local/lib/python3.9/site-packages/llmx
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
